In [1]:
#imports
import numpy as np
import random
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Importing sklearn Packages

from sklearn.neighbors import NearestNeighbors
#from sklearn.preprocessing import StandardScaler
#from sklearn.metrics import mean_squared_error, mean_absolute_error, accuracy_score, recall_score, precision_score
#from sklearn.metrics import plot_confusion_matrix
#from sklearn.metrics import confusion_matrix

In [2]:
df=pd.read_csv("capstone_project_dataset.csv")

In [3]:
df

Unnamed: 0  User ID              City  User Longitude  User Latitude  \
0             0      317            Jeddah       39.218564      21.736983   
1             1      415            Riyadh       46.937884      24.551856   
2             2      425            Riyadh       46.501978      24.699156   
3             3      456  Eastern Province       52.528577      26.575229   
4             4      420  Eastern Province       53.446234      26.122919   
..          ...      ...               ...             ...            ...   
995         995      166            Jeddah       39.304262      21.655744   
996         996      293  Eastern Province       51.736019      21.813979   
997         997      247  Eastern Province       55.466600      22.179759   
998         998       31            Riyadh       46.847037      24.553088   
999         999      456            Riyadh       46.776845      24.806883   

           Resturant Name  Resturant Longitude  Resturant Latitude  \
0        Al-Saaj Al-Reefi            39.137253           21.621797   
1                   Lusin            46.683451           24.697821   
2            La Brasserie            46.684105           24.690431   
3         Manoosha Alreef            50.118295           26.445350   
4          Queen Of India            50.179829           26.328298   
..                    ...                  ...                 ...   
995                 Aromi            39.109269           21.603596   
996        Tandoori House            50.129764           26.303790   
997  Al-Sanbok Restaurant            50.220734           26.271833   
998            Al Orjouan            46.630201           24.665121   
999           Cafe Bateel            46.629385           24.756379   

                                            Categories  \
0    Fast Food, Middle Eastern, Lebanese, Mediterra...   
1              Mediterranean, Middle Eastern, Armenian   
2                                French, International   
3    Lebanese, Fast Food, Mediterranean, Middle Eas...   
4                                               Indian   
..                                                 ...   
995                   Italian, Mediterranean, European   
996                                             Indian   
997              Seafood, International, Mediterranean   
998       Mediterranean, Middle Eastern, International   
999                      Cafe, Healthy, Middle Eastern   

                                         Special Diets  Review Score  \
0                                                  Non           4.0   
1    Vegetarian Friendly, Vegan Options, Gluten Fre...           4.6   
2                   Vegetarian Friendly, Vegan Options           2.7   
3                   Vegetarian Friendly, Vegan Options           4.7   
4    Vegetarian Friendly, Vegan Options, Gluten Fre...           4.9   
..                                                 ...           ...   
995  Vegetarian Friendly, Vegan Options, Gluten Fre...           2.8   
996                                                Non           4.6   
997  Vegetarian Friendly, Vegan Options, Gluten Fre...           4.2   
998  Vegetarian Friendly, Vegan Options, Gluten Fre...           3.6   
999  Vegetarian Friendly, Vegan Options, Gluten Fre...           3.0   

                                              Comments  
0                              Wow... Loved this place  
1                                   Crust is not good.  
2            Not tasty and the texture was just nasty.  
3    Stopped by during the late May bank holiday of...  
4    The selection on the menu was great and so wer...  
..                                                 ...  
995           I can't tell you how disappointed I was.  
996  I think food should have flavor and texture an...  
997                           Appetite instantly gone.  
998  Overall I was not impressed and would not go b...  
999  Then, as if I hadn't wasted enough of my life

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Unnamed: 0           1000 non-null   int64  
 1   User ID              1000 non-null   int64  
 2   City                 1000 non-null   object 
 3   User Longitude       1000 non-null   float64
 4   User Latitude        1000 non-null   float64
 5   Resturant Name       1000 non-null   object 
 6   Resturant Longitude  1000 non-null   float64
 7   Resturant Latitude   1000 non-null   float64
 8   Categories           1000 non-null   object 
 9   Special Diets        1000 non-null   object 
 10  Review Score         1000 non-null   float64
 11  Comments             1000 non-null   object 
dtypes: float64(5), int64(2), object(5)
memory usage: 93.9+ KB


In [5]:
model1 = NearestNeighbors(n_neighbors=4)
model1.fit(df[['Resturant Longitude', 'Resturant Latitude']])

NearestNeighbors(n_neighbors=4)

In [6]:
model1.kneighbors([df.iloc[0, 3:5]], return_distance=True)

(array([[0.14099421, 0.14099421, 0.14099421, 0.14099421]]),
 array([[280, 281, 958,   0]], dtype=int64))

In [10]:
df.iloc[281, :]

Unnamed: 0                                                           281
User ID                                                              238
City                                                              Jeddah
User Longitude                                                   39.2983
User Latitude                                                    21.8659
Resturant Name                                          Al-Saaj Al-Reefi
Resturant Longitude                                              39.1373
Resturant Latitude                                               21.6218
Categories             Fast Food, Middle Eastern, Lebanese, Mediterra...
Special Diets                                                        Non
Review Score                                                         4.2
Comments               I would definitely recommend the wings as well...
Name: 281, dtype: object

In [8]:
model1.kneighbors([df.iloc[120, 3:5]], return_distance=True)

(array([[0.29740441, 0.29740441, 0.29740441, 0.29740441]]),
 array([[107,  10,  50, 566]], dtype=int64))